name: Deploy API

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        run: |
          git clone https://github.com/RodrigoSester/volleyhub-api.git
          cd volleyhub-api/
          git checkout development

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 46.202.151.126 >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Copy files via rsync
        run: |
          rsync -avz --delete -e ssh . github-actions@46.202.151.126:/home/github-actions/workspace/volleyhub/volleyhub-api

      - name: Install dependencies and start application (using SSH)
        run: |
          ssh github-actions@46.202.151.126 << 'EOF'
            ls -la
            cd home/github-actions/workspace/volleyhub/volleyhub-api
            npm install
            pm2 restart all || pm2 start index.js
          EOF