name: Deploy API

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        run: |
          git clone https://github.com/RodrigoSester/volleyhub-api.git
          cd volleyhub-api/
          git checkout development

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/ghactions_id_rsa
          ssh-keyscan -H 46.202.151.126 >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add ~/ghactions_id_rsa

      - name: Copy files via rsync (recommended for efficiency)
        run: |
          rsync -avz --delete -e ssh . ghactions@46.202.151.126:/workspace/volleyhub/volleyhub-api

      - name: Install dependencies and start application (using SSH)
        run: |
          ssh ghactions@46.202.151.126 << 'EOF'
            cd /workspace/volleyhub/volleyhub-api
            npm install
            pm2 restart all || pm2 start index.js
          EOF